name: urbansafe_app
description: UrbanSafe - Navigasi Keamanan Transportasi Publik

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^13.2.0

  # Database
  drift: ^2.18.0
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.24
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # Auth & Security
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  crypto: ^3.0.3

  # HTTP & API
  dio: ^5.6.0

  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  flutter_compass: ^0.8.0

  # Sensors
  sensors_plus: ^4.0.2

  # Notifications
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1

  # Image
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # UI
  flutter_animate: ^4.5.0
  fl_chart: ^0.69.0
  shimmer: ^3.0.0

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  path: ^1.9.0
  connectivity_plus: ^6.0.5
  package_info_plus: ^8.1.2
  url_launcher: ^6.3.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  drift_dev: ^2.18.0
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/models/
